src/Entity/Leader.php
<?php

namespace App\Entity;

use App\Entity\Traits\CoreEntityTrait;
use App\Repository\LeaderRepository;
use App\Service\RoleManager\Role;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: LeaderRepository::class)]
class Leader implements UserInterface, PasswordAuthenticatedUserInterface
{
    use CoreEntityTrait;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    private ?string $plainPassword;

    #[ORM\OneToOne(targetEntity: Person::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name: 'person_id', referencedColumnName: 'id', nullable: false)]
    private ?Person $person = null;

    #[ORM\OneToOne(mappedBy: 'leader', cascade: ['persist', 'remove'])]
    private ?LaunchPointContacts $launchPointContact = null;

    /**
     * !! KEY OVERLAP ISSUES - SET TO TRUE IF IT COULD HAPPEN !!
     *
     * @param bool $forceMerge this sets the key to the role that is default,
     *                         This will make sure when providing Instance
     *                         Roles we don't overwrite anything while including this role as well
     */
    public static function DEFAULT_ROLES(bool $forceMerge = false): array
    {
        if ($forceMerge) {
            return [Role::DEFAULT => Role::DEFAULT];
        }

        return [Role::DEFAULT];
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;
        $this->getPerson()?->setEmail($email);

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        // guarantee every user at least has ROLE_USER
        $roles = array_merge(
            $this->roles,
            self::DEFAULT_ROLES(true)
        );

        return array_unique(array_values($roles));
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function getFullName(): string
    {
        return $this->getPerson()->getFullName();
    }

    public function getPerson(): ?Person
    {
        return $this->person;
    }

    public function setPerson(Person $person): self
    {
        $this->person = $person;

        return $this;
    }

    public function getLaunchPoint(): ?Location
    {
        return $this->getLaunchPointContact()?->getLaunchPoint();
    }

    public function __toString(): string
    {
        $person = $this->getPerson();

        return $person->getFullName()." ({$this->getEmail()})";
    }

    public function getLaunchPointContact(): ?LaunchPointContacts
    {
        return $this->launchPointContact;
    }

    public function setLaunchPointContact(LaunchPointContacts $launchPointContact): static
    {
        // set the owning side of the relation if necessary
        if ($launchPointContact->getLeader() !== $this) {
            $launchPointContact->setLeader($this);
        }

        $this->launchPointContact = $launchPointContact;

        return $this;
    }
}

src/Entity/Location.php
<?php

namespace App\Entity;

use App\Entity\Traits\AddressTrait;
use App\Entity\Traits\CoreEntityTrait;
use App\Enum\EventParticipantStatusEnum;
use App\Repository\LocationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Order;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;
use JetBrains\PhpStorm\ArrayShape;
use ReflectionClass;

#[ORM\Entity(repositoryClass: LocationRepository::class)]
class Location
{
    use CoreEntityTrait;
    use AddressTrait;

    public const TYPE_LAUNCH_POINT = 'launch';
    public const TYPE_EVENT = 'event';

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'location', targetEntity: Event::class)]
    private Collection $events; // this field is for self::TYPE_EVENT only

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\OneToMany(mappedBy: 'launchPoint', targetEntity: EventParticipant::class)]
    private Collection $eventAttendees;

    #[ORM\ManyToMany(targetEntity: Event::class, mappedBy: 'launchPoints')]
    private Collection $launchPointEvents; // this field is for self::TYPE_LAUNCH_POINT only

    #[ORM\Column(nullable: true)]
    private ?array $geolocation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pinColor = null;

    #[ORM\Column()]
    private bool $active = true;

    /**
     * @var Collection<int, LaunchPointContacts>
     */
    #[ORM\OneToMany(mappedBy: 'launchPoint', targetEntity: LaunchPointContacts::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $launchPointContacts;

    #[ORM\Column(options: ['default' => true])]
    private ?bool $shareLocationContactDetails = null;

    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->eventAttendees = new ArrayCollection();
        $this->launchPointEvents = new ArrayCollection();
        $this->launchPointContacts = new ArrayCollection();
    }

    public function getShortAddress(): string
    {
        $city = empty($city = $this->getCity() ?? '') ? $city : $city.', ';
        $state = empty($state = $this->getState() ?? '') ? $state : $state.' ';
        $zip = $this->getZipcode() ?? '';

        return $city.$state.$zip;
    }

    public function getLongAddress(bool $url = false): string
    {
        $cityStateZip = $this->getShortAddress();

        if ($url) {
            return urlencode($this->getLine1().', '.$cityStateZip.', '.$this->getCountry());
        }

        return $this->getLine1()."\n".$cityStateZip."\n".$this->getCountry();
    }

    public function getName(bool $truncate = false): ?string
    {
        if ($truncate && (strlen($this->name) > 31)) {
            return substr($this->name, 0, 28).'...';
        }

        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public static function TYPES(): array
    {
        $oClass = new ReflectionClass(static::class);

        return $oClass->getConstants();
    }

    /**
     * @return Collection<int, Event>
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events->add($event);
            $event->setLocation($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getLocation() === $this) {
                $event->setLocation(null);
            }
        }

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        if (!in_array($type, self::TYPES())) {
            throw new InvalidArgumentException('Invalid Type provided for Location');
        }

        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, EventParticipant>
     */
    public function getEventAttendees(): Collection
    {
        return $this->eventAttendees;
    }

    public function getAttendingEventAttendees(): Collection
    {
        $criteria = Criteria::create()
            ->orderBy(['person.firstName' => Order::Ascending]);

        return $this->getEventAttendees()->filter(function (EventParticipant $eventAttendee) {
            return $eventAttendee->getStatus() === EventParticipantStatusEnum::ATTENDING->value;
        })->matching($criteria);
    }

    public function addEventAttendee(EventParticipant $eventAttendee): self
    {
        if (!$this->eventAttendees->contains($eventAttendee)) {
            $this->eventAttendees->add($eventAttendee);
            $eventAttendee->setLaunchPoint($this);
        }

        return $this;
    }

    public function removeEventAttendee(EventParticipant $eventAttendee): self
    {
        if ($this->eventAttendees->removeElement($eventAttendee)) {
            // set the owning side to null (unless already changed)
            if ($eventAttendee->getLaunchPoint() === $this) {
                $eventAttendee->setLaunchPoint(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Event>
     */
    public function getLaunchPointEvents(): Collection
    {
        return $this->launchPointEvents;
    }

    public function addLaunchPointEvent(Event $launchPointEvent): self
    {
        if (!$this->launchPointEvents->contains($launchPointEvent)) {
            $this->launchPointEvents->add($launchPointEvent);
            $launchPointEvent->addLaunchPoint($this);
        }

        return $this;
    }

    public function removeLaunchPointEvent(Event $launchPointEvent): self
    {
        if ($this->launchPointEvents->removeElement($launchPointEvent)) {
            $launchPointEvent->removeLaunchPoint($this);
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName() ?? '';
    }

    #[ArrayShape(['latitude' => 'int', 'longitude' => 'int', 'color' => 'string', 'status' => 'string'])]
    public function getGeolocation(): ?array
    {
        return $this->geolocation;
    }

    public function setGeolocation(?array $geolocation): static
    {
        $this->geolocation = $geolocation;

        return $this;
    }

    public function hasMappingLocation(): bool
    {
        if (!$this->getGeolocation()) {
            return false;
        }

        if ('SUCCESS' !== $this->getGeolocation()['status']) {
            return false;
        }

        return true;
    }

    public function getLatitude(): ?float
    {
        return $this->getGeolocation()['latitude'] ?? null;
    }

    public function getLongitude(): ?float
    {
        return $this->getGeolocation()['longitude'] ?? null;
    }

    /**
     * @return Collection<int, Leader>
     */
    public function getLaunchPointContacts(): Collection
    {
        return $this->launchPointContacts;
    }

    public function getLaunchPointContactLeaders(): Collection
    {
        $mainLeaders = Criteria::create()
            ->andWhere(
                Criteria::expr()->eq('helper', false),
            );

        return $this->launchPointContacts->matching($mainLeaders);
    }

    public function getLaunchPointContactHelpers(): Collection
    {
        $mainLeaders = Criteria::create()
            ->andWhere(
                Criteria::expr()->eq('helper', true),
            );

        return $this->launchPointContacts->matching($mainLeaders);
    }

    public function addLaunchPointContact(LaunchPointContacts $launchPointContact): static
    {
        if (!$this->launchPointContacts->contains($launchPointContact)) {
            $this->launchPointContacts->add($launchPointContact);
            $launchPointContact->setLaunchPoint($this);
        }

        return $this;
    }

    public function removeLaunchPointContact(LaunchPointContacts $launchPointContact): static
    {
        if ($this->launchPointContacts->removeElement($launchPointContact)) {
            // set the owning side to null (unless already changed)
            if ($launchPointContact->getLaunchPoint() === $this) {
                $launchPointContact->setLaunchPoint(null);
            }
        }

        return $this;
    }

    public function getPinColor(): ?string
    {
        return $this->pinColor;
    }

    public function setPinColor(string $pinColor): static
    {
        $this->pinColor = $pinColor;

        return $this;
    }

    public function isActive(): bool
    {
        return $this->active;
    }

    public function setActive(bool $active): void
    {
        $this->active = $active;
    }

    public function getChartData(): ?array
    {
        return [
            'name' => $this->getName(),
            'attendees' => $this->getEventAttendees(),
            'servers' => 15,
        ];
    }

    public function isShareLocationContactDetails(): ?bool
    {
        return $this->shareLocationContactDetails;
    }

    public function setShareLocationContactDetails(bool $shareLocationContactDetails): static
    {
        $this->shareLocationContactDetails = $shareLocationContactDetails;

        return $this;
    }
}

src/Entity/Person.php
<?php

namespace App\Entity;

use App\Entity\Traits\CoreEntityTrait;
use App\Repository\PersonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PersonRepository::class)]
class Person
{
    use CoreEntityTrait;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    protected ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    protected ?string $phone = null;

    #[ORM\OneToMany(mappedBy: 'details', targetEntity: ContactPerson::class, orphanRemoval: true)]
    private Collection $contactFor;

    #[ORM\OneToMany(mappedBy: 'person', targetEntity: EventParticipant::class, orphanRemoval: true)]
    private Collection $attendedEvents;

    public function __construct()
    {
        $this->contactFor = new ArrayCollection();
        $this->attendedEvents = new ArrayCollection();
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection<int, ContactPerson>
     */
    public function getContactFor(): Collection
    {
        return $this->contactFor;
    }

    public function addContactFor(ContactPerson $contactFor): self
    {
        if (!$this->contactFor->contains($contactFor)) {
            $this->contactFor->add($contactFor);
            $contactFor->setDetails($this);
        }

        return $this;
    }

    public function removeContactFor(ContactPerson $contactFor): self
    {
        if ($this->contactFor->removeElement($contactFor)) {
            // set the owning side to null (unless already changed)
            if ($contactFor->getDetails() === $this) {
                $contactFor->setDetails(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, EventParticipant>
     */
    public function getAttendedEvents(): Collection
    {
        return $this->attendedEvents;
    }

    public function addAttendedEvent(EventParticipant $attendedEvent): self
    {
        if (!$this->attendedEvents->contains($attendedEvent)) {
            $this->attendedEvents->add($attendedEvent);
            $attendedEvent->setPerson($this);
        }

        return $this;
    }

    public function removeAttendedEvent(EventParticipant $attendedEvent): self
    {
        if ($this->attendedEvents->removeElement($attendedEvent)) {
            // set the owning side to null (unless already changed)
            if ($attendedEvent->getPerson() === $this) {
                $attendedEvent->setPerson(null);
            }
        }

        return $this;
    }

    public function getFullName(): string
    {
        return $this->getFirstName().' '.$this->getLastName();
    }

    public function getInitials(): string
    {
        $firstName = $this->getFirstName();
        $lastName = $this->getLastName();

        return strtoupper(
            substr($firstName, 0, 1).
            substr($lastName, 0, 1)
        );
    }

    public function __toString(): string
    {
        return $this->getFirstName().' '.$this->getLastName();
    }
}

templates/tailwind/checkin-form.html.twig
{% extends 'tailwind/Components/base.modal.html.twig' %}

{% form_theme form '@TalesFromADevFlowbite/form/default.html.twig' %}

{% block content %}
    <turbo-frame id="modal">
        {{ form_start(form) }}
        {% set participant = form.vars.value %}
        <div class="py-4 md:py-8">
            <div class="mb-4 grid gap-4 sm:grid-cols-2 sm:gap-8 lg:gap-16">
                <div class="space-y-4">
                    <div class="flex items-center">
                        <!-- Person avatar/icon -->
                        <div class="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center">
                            <span class="text-gray-600 font-medium">
                                {{ participant.person.initials }}
                            </span>
                        </div>
                        <div class="ml-4">
                            <div class="font-medium text-gray-900">{{ participant.person.fullName }}</div>
                            <div class="text-gray-500">{{ participant.person.email }}</div>
                        </div>
                    </div>
                </div>
                <div class="space-y-4">
                    <div class="flex items-center">
                        <div class="ml-4">
                            <div class="font-medium text-gray-900">Payment Time</div>
                            <div class="text-gray-500">{{ participant.paymentMethod }}</div>
                        </div>
{#                        <div class="flex items-center space-x-4 text-gray-500">#}
{#                            <div>#}
{#                                {{ form_row(form.paymentMethod) }}#}
{#                            </div>#}
{#                        </div>#}
                    </div>
                </div>
            </div>
            <div class="mt-4 flex w-full gap-4">
{#                <div class="w-1/2">#}
                    {{ form_row(form.PayAtEncounter) }}
{#                </div>#}
{#                <div class="w-1/2">#}
                    {{ form_row(form.PaidAlready) }}
{#                </div>#}

            </div>
        </div>
        {{ form_rest(form) }}
        {{ form_end(form) }}
    </turbo-frame>
{% endblock %}

templates/tailwind/checkin.html.twig
{% extends 'tailwind.base.html.twig' %}

{% block content %}
    {% if useMercure %}
        <div {{ stimulus_controller('mercure-server-checkin', {
            mercureUrl: mercure('server-training-checkin'),
        }) }}></div>
    {% endif %}
    <div class="px-4 sm:px-6 lg:px-8 mx-auto px-4 py-8">
        <div class="sm:flex sm:items-center  overflow-hidden">
            <div class="sm:flex-auto mb-3">
                <h1 class="text-lg font-semibold leading-6 text-gray-900">Server Training - Checkin</h1>
                <p class="mt-2 text-sm text-gray-700">A list of all the registered servers grouped by launch point.</p>
            </div>
            <div class="fixed right-[-7rem] h-auto w-48 sm:hidden md:flex z-30">
                <img src="{{ asset('static/images/JesusPeaking.png') }}" alt="" class="relative h-auto w-28 -rotate-[30deg]">
            </div>
        </div>
        <!-- Header Row -->
        <div class="grid grid-cols-5 gap-4 py-3 border-b border-gray-200 text-sm font-medium text-gray-500 sticky top-0 bg-white z-20">
            <div></div>
            <div>Name</div>
            <div>Status</div>
            <div>Prayer Team</div>
            <div>Payment</div>
        </div>


        <div class="py-3 border-b border-gray-200">
            {% for launch in launches %}
                <!-- Group: Launch Point -->
                <div class="px-4 py-2 font-bold text-2xl mb-2 bg-gray-200 sticky top-14 z-10"> {{ launch.name }}</div>

                {% for participant in launch.attendingEventAttendees %}
                    {% if participant.type == 'server' and participant.event.id == event.id %}
{#                        {% include 'tailwind/Components/streams/server_checkin_row.html.twig' with {participant: participant} %}#}
                        <turbo-frame id="participant-{{ participant.id }}">
                            <twig:Taig:ServerRegistrationDetailRow
                                    :participant="participant"
                                    key="{{ participant.id }}"
                            />
                        </turbo-frame>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </div>



    </div>


{% endblock %}