src/Entity/Location.php
<?php

namespace App\Entity;

use App\Entity\Traits\AddressTrait;
use App\Entity\Traits\CoreEntityTrait;
use App\Enum\EventParticipantStatusEnum;
use App\Repository\LocationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Order;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;
use JetBrains\PhpStorm\ArrayShape;
use ReflectionClass;

#[ORM\Entity(repositoryClass: LocationRepository::class)]
class Location
{
    use CoreEntityTrait;
    use AddressTrait;

    public const TYPE_LAUNCH_POINT = 'launch';
    public const TYPE_EVENT = 'event';

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'location', targetEntity: Event::class)]
    private Collection $events; // this field is for self::TYPE_EVENT only

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\OneToMany(mappedBy: 'launchPoint', targetEntity: EventParticipant::class)]
    private Collection $eventAttendees;

    #[ORM\ManyToMany(targetEntity: Event::class, mappedBy: 'launchPoints')]
    private Collection $launchPointEvents; // this field is for self::TYPE_LAUNCH_POINT only

    #[ORM\Column(nullable: true)]
    private ?array $geolocation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pinColor = null;

    #[ORM\Column()]
    private bool $active = true;

    /**
     * @var Collection<int, LaunchPointContacts>
     */
    #[ORM\OneToMany(mappedBy: 'launchPoint', targetEntity: LaunchPointContacts::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $launchPointContacts;

    #[ORM\Column(options: ['default' => true])]
    private ?bool $shareLocationContactDetails = null;

    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->eventAttendees = new ArrayCollection();
        $this->launchPointEvents = new ArrayCollection();
        $this->launchPointContacts = new ArrayCollection();
    }

    public function getShortAddress(): string
    {
        $city = empty($city = $this->getCity() ?? '') ? $city : $city.', ';
        $state = empty($state = $this->getState() ?? '') ? $state : $state.' ';
        $zip = $this->getZipcode() ?? '';

        return $city.$state.$zip;
    }

    public function getLongAddress(bool $url = false): string
    {
        $cityStateZip = $this->getShortAddress();

        if ($url) {
            return urlencode($this->getLine1().', '.$cityStateZip.', '.$this->getCountry());
        }

        return $this->getLine1()."\n".$cityStateZip."\n".$this->getCountry();
    }

    public function getName(bool $truncate = false): ?string
    {
        if ($truncate && (strlen($this->name) > 31)) {
            return substr($this->name, 0, 28).'...';
        }

        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public static function TYPES(): array
    {
        $oClass = new ReflectionClass(static::class);

        return $oClass->getConstants();
    }

    /**
     * @return Collection<int, Event>
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events->add($event);
            $event->setLocation($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getLocation() === $this) {
                $event->setLocation(null);
            }
        }

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        if (!in_array($type, self::TYPES())) {
            throw new InvalidArgumentException('Invalid Type provided for Location');
        }

        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, EventParticipant>
     */
    public function getEventAttendees(): Collection
    {
        return $this->eventAttendees;
    }

    public function getAttendingEventAttendees(): Collection
    {
        $criteria = Criteria::create()
            ->orderBy(['person.firstName' => Order::Ascending]);

        return $this->getEventAttendees()->filter(function (EventParticipant $eventAttendee) {
            return $eventAttendee->getStatus() === EventParticipantStatusEnum::ATTENDING->value;
        })->matching($criteria);
    }

    public function addEventAttendee(EventParticipant $eventAttendee): self
    {
        if (!$this->eventAttendees->contains($eventAttendee)) {
            $this->eventAttendees->add($eventAttendee);
            $eventAttendee->setLaunchPoint($this);
        }

        return $this;
    }

    public function removeEventAttendee(EventParticipant $eventAttendee): self
    {
        if ($this->eventAttendees->removeElement($eventAttendee)) {
            // set the owning side to null (unless already changed)
            if ($eventAttendee->getLaunchPoint() === $this) {
                $eventAttendee->setLaunchPoint(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Event>
     */
    public function getLaunchPointEvents(): Collection
    {
        return $this->launchPointEvents;
    }

    public function addLaunchPointEvent(Event $launchPointEvent): self
    {
        if (!$this->launchPointEvents->contains($launchPointEvent)) {
            $this->launchPointEvents->add($launchPointEvent);
            $launchPointEvent->addLaunchPoint($this);
        }

        return $this;
    }

    public function removeLaunchPointEvent(Event $launchPointEvent): self
    {
        if ($this->launchPointEvents->removeElement($launchPointEvent)) {
            $launchPointEvent->removeLaunchPoint($this);
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName() ?? '';
    }

    #[ArrayShape(['latitude' => 'int', 'longitude' => 'int', 'color' => 'string', 'status' => 'string'])]
    public function getGeolocation(): ?array
    {
        return $this->geolocation;
    }

    public function setGeolocation(?array $geolocation): static
    {
        $this->geolocation = $geolocation;

        return $this;
    }

    public function hasMappingLocation(): bool
    {
        if (!$this->getGeolocation()) {
            return false;
        }

        if ('SUCCESS' !== $this->getGeolocation()['status']) {
            return false;
        }

        return true;
    }

    public function getLatitude(): ?float
    {
        return $this->getGeolocation()['latitude'] ?? null;
    }

    public function getLongitude(): ?float
    {
        return $this->getGeolocation()['longitude'] ?? null;
    }

    /**
     * @return Collection<int, Leader>
     */
    public function getLaunchPointContacts(): Collection
    {
        return $this->launchPointContacts;
    }

    public function getLaunchPointContactLeaders(): Collection
    {
        $mainLeaders = Criteria::create()
            ->andWhere(
                Criteria::expr()->eq('helper', false),
            );

        return $this->launchPointContacts->matching($mainLeaders);
    }

    public function getLaunchPointContactHelpers(): Collection
    {
        $mainLeaders = Criteria::create()
            ->andWhere(
                Criteria::expr()->eq('helper', true),
            );

        return $this->launchPointContacts->matching($mainLeaders);
    }

    public function addLaunchPointContact(LaunchPointContacts $launchPointContact): static
    {
        if (!$this->launchPointContacts->contains($launchPointContact)) {
            $this->launchPointContacts->add($launchPointContact);
            $launchPointContact->setLaunchPoint($this);
        }

        return $this;
    }

    public function removeLaunchPointContact(LaunchPointContacts $launchPointContact): static
    {
        if ($this->launchPointContacts->removeElement($launchPointContact)) {
            // set the owning side to null (unless already changed)
            if ($launchPointContact->getLaunchPoint() === $this) {
                $launchPointContact->setLaunchPoint(null);
            }
        }

        return $this;
    }

    public function getPinColor(): ?string
    {
        return $this->pinColor;
    }

    public function setPinColor(string $pinColor): static
    {
        $this->pinColor = $pinColor;

        return $this;
    }

    public function isActive(): bool
    {
        return $this->active;
    }

    public function setActive(bool $active): void
    {
        $this->active = $active;
    }

    public function getChartData(): ?array
    {
        return [
            'name' => $this->getName(),
            'attendees' => $this->getEventAttendees(),
            'servers' => 15,
        ];
    }

    public function isShareLocationContactDetails(): ?bool
    {
        return $this->shareLocationContactDetails;
    }

    public function setShareLocationContactDetails(bool $shareLocationContactDetails): static
    {
        $this->shareLocationContactDetails = $shareLocationContactDetails;

        return $this;
    }
}

templates/frontend/_main_menu.nav.html.twig
<nav class="navbar navbar-expand-lg fixed-top" id="mainNav">
    <div class="container-fluid px-4 px-lg-5">
        <a class="navbar-brand" href="{{ path('app_index') }}#page-top">
            <img src="{{ asset('static/images/logo.png') }}" height="60" alt="Encounter the Cross Logo">
                <span class="d-none d-md-inline">Encounter The Cross
                {% if app.environment != 'prod' %} - <span class="text-primary">{{ app.environment|upper }}</span>{% endif %}</span>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
<!--            <ul class="navbar-nav ms-auto">-->
                {{ knp_menu_render('main') }}
<!--                <li class="nav-item"><a class="nav-link" href="#about">About</a></li>-->
<!--                <li class="nav-item"><a class="nav-link" href="#projects">Projects</a></li>-->
<!--                <li class="nav-item"><a class="nav-link" href="#signup">Contact</a></li>-->
<!--            </ul>-->
        </div>
    </div>
</nav>

templates/frontend/index.html.twig
{% extends 'bootstrap.base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
{#    {{ encore_entry_script_tags('event-counter') }}#}
{% endblock %}
{% block importmap %}{{ importmap(['app','app_event_counter']) }}{% endblock %}

{% block masthead %}
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 d-flex flex-column align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">Galatians 5:1</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5 ">It is for freedom that christ has set us free.</h2>
                    {% if event is not null and event.start > date('now') %}
                        <h2 class="text-white-50 mx-auto mt-2 mb-4 ">{{ event.start|date("F d") }}-{{ event.end|date("d") }}, {{ event.start|date("Y") }}</h2>
                        <div id="flip" class="mb-4 text-white d-flex justify-content-evenly" data-next-encounter="{{ event.start|date('c', "America/Chicago") }}">
                        </div>
                    {% else %}
                        <h2 class="text-white-50 mx-auto mt-2 mb-4 ">{{ event.start|date("F d") }}-{{ event.end|date("d") }}, {{ event.start|date("Y") }}</h2>
                        <h3 class="text-uppercase text-white-50">Happening Now</h3>

                        <div class="mb-4 text-white d-flex justify-content-evenly">
                            <a class="btn btn-primary m-2" href="{{ path('app_registration_list') }}">Look at Upcoming Encounters</a>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% if event is not null and event.start > date('now') and event.registrationStarted %}
                <div class="d-flex flex-column flex-md-row justify-content-md-around">
                    {% if waitlist_enabled %}
                        <a class="btn btn-primary m-2" href="{{ path('app_registration_attendee_formentry',{'event': event.id}) }}">Attendee Waiting List</a>
                    {% else %}
                        <a class="btn btn-primary m-2" href="{{ path('app_registration_attendee_formentry',{'event': event.id}) }}">Attendee Register</a>
                    {% endif %}
                    
                    {% if event.canServerRegister %}
                        <a class="btn btn-outline-light m-2" href="{{ path('app_registration_server_formentry',{'event': event.id}) }}">Server Register</a>
                    {% endif %}
                </div>
            {% endif %}
            {% if not event.registrationStarted %}
                <div>
                    <p class="text-white-50 mx-auto mt-2 mb-5 text-center">
                        Join us for a transformative weekend as we explore true freedom in Christ.
                    </p>
                    <p class="text-info text-center">Stay tuned for registration details.</p>

                </div>
            {% endif %}
        </div>
    </header>
{% endblock %}

{% block about %}
    <section class="about-section" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <h2 class="text-white mb-4">About Men's Encounter</h2>
                <div class="accordion" id="accordionExample">
                    <div class="accordion-item">
                        <p class="accordion-header mb-0" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                What is Men's Encounter?
                            </button>
                        </p>
                        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                Men’s Encounter is a time for us men to get away and encounter God, perhaps like never before; a time to consider, give thought to our lives, and discover solutions to the unique challenges facing men.
                                <br><br>
                                Who would you like to provide solutions for you?  Who better than God?
                                <br><br>
                                It is important to take the time to step away and gain perspective.  Whether you think you have it all figured out or not, you will benefit from attending and you will come home with no regrets.  From the time you leave until the time you return, you will have nothing to worry about; all meals, transportation and lodging is included.
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <p class="accordion-header mb-0" id="headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Encounter Weekend
                            </button>
                        </p>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                Most likely you were directed here by a friend, and you may be wondering "what in the world is this guy so excited about?"  Well, take any ideas you may have about this impactful event and throw them out the window.  You can be as social or hermit-like as you wish - you will not be forced out of your comfort zone.  Don’t worry, this is not another church retreat; there will not be: a bunch of dudes holding hands singing kumbaya, sleep-deprived group-therapy, or any other such nonsense.  Life is a series of choices, and at a minimum, this is an opportunity to receive something that equips you to face life’s challenges in an environment customized for you.
                                <br><br>
                                The Men’s Encounter is organized by men and for men.  There is no central organization, but rather a growing network of men from all walks of life and many different regions that have experienced freedom and are now working to share it with others.
                                <br><br>
                                The principles and tools shared are foundational in nature, but yet can have a profound influence on those who come with a humble and open heart.  While there will be other men in attendance, Encounter is an individual and personal experience.  What takes place during the weekend is between you and God.  He has a gift uniquely for you.
                                <br><br>
                                Hope to see you there!
                                <div class="text-center">
                                    <a class="btn btn-primary" href="{{ path('app_registration_attendee_formentry',{'event': event.id}) }}">Attendee Register</a>
                                    <a class="btn btn-primary" href="{{ path('app_registration_server_formentry',{'event': event.id}) }}">Server Register</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <p class="accordion-header mb-0" id="headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Launch Points
                            </button>
                        </p>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                The Men's Encounter is being hosted by several different communities.  For your convenience, we have designated different "Launch Points."  You will choose one of these points during your registration.  This will be the place that you start your Encounter.  Once you have arrived, we will have a brief meeting, and will then depart as a group for the Encounter location.  All the men from the different Launch Points will arrive at Encounter at the same time.  You will need to arrive at your Launch Point by the time stated on your confirmation email.
                                <h3 class="mt-2 mb-4">What to Bring</h3>
                                <ul>
                                    <li>Sleeping bag/Bed covering & pillow</li>
                                    <li>Comfortable Shoes</li>
                                    <li>Towels</li>
                                    <li>Toiletries (soap, deodorant, etc.)</li>
                                    <li>Bible (Do not pack, you will need it at pre-encounter)</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <p class="accordion-header mb-0" id="headingFour">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                Cost
                            </button>
                        </p>
                        <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                There is a registration charge, but don't let that stop you; if it is a problem, scholarships are available.  You can write a check to Men's Encounter and mail it to your Launch Point, or you can pay by cash or check upon arrival.
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <img class="img-fluid" src="{{ asset('static/images/HillCross.png') }}"  alt="Cross on a hill" />
        </div>
    </section>
{% endblock %}

{% block projects %}
    <section class="content-section bg-light" id="testimonials">
        <div class="container px-4 px-lg-5">
            <!-- Featured Project Row-->
{#            {{ component('testimonial',{#}
{#                featured: true,#}
{#                name: 'Jordan',#}
{#                quote: 'this is a test to test the testing of this test.'#}
{#            }) }}#}
{#            {% for testimony in testimonies %}#}
            {# : 'HalfLeft', #}
                {{ component('TestimonialCollectionComponent',{
                    layout: 'HalfRight',
                    limit: 2,
                    request: app.request,
                }) }}
{#            {% endfor %}#}
            <div class="d-flex mt-4 justify-content-center">
                <a role="button" href="{{ path('app_testimonies') }}" class="btn btn-outline-dark">More Testimonials <i class="fa-solid fa-angles-right fa-fade fa-sm"></i></a>
            </div>
        </div>
    </section>
{% endblock %}

{% block signup %}
{% endblock %}

templates/frontend/launchpoints.html.twig
{% extends 'frontend/blank_content.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('map-launch-points') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('map-launch-points') }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col text-center">
            <i class="fa-solid fa-place-of-worship fa-2xl mb-2 text-dark"></i>
            <h1 class="text-dark mb-5 display-1">Contact</h1>
            <hr>
        </div>
    </div>
{#    <div class="row map-row mb-3">#}
{#        <div class="col-12 map-background-container p-0 m-0">#}
{#            <div id="map" data-pins="{{ map_pins|json_encode }}" class="map-container"></div>#}
{#        </div>#}
{#    </div>#}

    {{ component('contact_event_leaders') }}
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 mb-3">
        {% for launchPoint in launch_points %}
            <div class="col">
                <div class="card mb-3">
                    {#                            <img src="..." class="card-img-top" alt="...">#}
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item" style="--bs-bg-opacity: 1;background-color: {{ launchPoint.pinColor }} !important;"></li>
                    </ul>
                    <div class="card-header p-0 mb-2 mt-3 bg-white">
                        <p class="h-5 text-center">Launch Point Contact</p>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ launchPoint.name }}</h5>
                        <div class="row justify-content-center">
                            <div class="col-8">
                                <address>{{ launchPoint.longAddress }}</address>
                            </div>
                        </div>
                        <hr>
                        {% for leaderJoin in launchPoint.launchPointContactLeaders %}
                            {% set leader = leaderJoin.leader %}
                            <div class="row mb-3">
                                <div class="col">
                                    <div class="row">
                                        <div class="col">
                                            <h5 class="card-title">{{ leader.person.firstName }} {{ leader.person.lastName }}</h5>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            {% if leader.person.email %}
                                                <div class="row">
                                                    <div class="col-9">
                                                        <i class="fas fa-envelope text-primary"></i>
                                                        <a class="text-start text-decoration-none" href="mailto:{{ leader.person.email }}">{{ leader.person.email }}</a>
                                                    </div>

                                                </div>
                                            {% endif %}
                                            {% if leader.person.phone %}
                                                <div class="row">
                                                    <div class="col-9">
                                                        <i class="fa-solid fa-phone text-primary"></i>
                                                        <a class=" text-decoration-none" href="tel:{{ leader.person.phone }}">{{ leader.person.phone }}</a>
                                                    </div>
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <p class="card-text">No Contact Available</p>
                        {% endfor %}

                    </div>
                    {% if launchPoint.longAddress %}
                        <div class="card-footer py-2 bg-white d-flex justify-content-evenly">
                            <a class=" text-decoration-none" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination={{ launchPoint.longAddress|url_encode }}">
                                <span class="text-black">Get Directions </span><i class="fa-solid fa-location-arrow fa-lg"></i>
                            </a>
                        </div>
                    {% endif %}

                </div>

            </div>
        {% else %}
            <h3>Sorry we are still setting up our launch points.</h3>
        {% endfor %}
    </div>
{#    {{ dump(launch_points) }}#}
{% endblock %}

templates/frontend/split.index.html.twig
<html>
<head><meta charset="us-ascii">
	<title>Encounter The Cross Launchpad</title>
	<style type="text/css">body
{
	background: black;
}
	</style>
</head>
<body>
<table style="width: 100%;height:100%;">
	<tbody>
		<tr>
			<td style="text-align: center;" valign="middle"><a href="https://women.encounterthecross.com"><img src="{{ asset('static/images/we.png') }}" /></a> &nbsp; &nbsp; <a href="/men/"><img src="{{ asset('static/images/me.png') }}" /></a></td>
		</tr>
	</tbody>
</table>
</body>
</html>